version: "3.8"

services:
  mongodb:
    image: mongo:6
    volumes:
      - db:/data/db

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic:/usr/share/elasticsearch/data

  minio:
    image: minio/minio:latest
    command: server /data
    volumes:
      - files:/data
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_DOMAIN=http://localhost:9000

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    depends_on: [mongodb]

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    depends_on: [account]

  fulltext:
    image: hardcoreeng/fulltext:${HULY_VERSION}
    depends_on: [account]

  stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    depends_on: [account]

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    depends_on: [account]

  rekoni:
    image: hardcoreeng/rekoni:${HULY_VERSION}
    depends_on: [account]

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    depends_on: [account]

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    depends_on: [account]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front

volumes:
  db:
  elastic:
  files:
